### ISSUE TITLE
The example image in the readme and inside Obsidian is broken

### ISSUE THREAD

**Issue by AmmarCodes** [Justin-Arnold/Journalyst#1]
![image](https://github.com/Justin-Arnold/Journalyst/assets/351256/a886d5d3-79fe-46df-867e-77288a478d99)

![image](https://github.com/Justin-Arnold/Journalyst/assets/351256/e2e61c09-89d0-44bf-8868-d57052ce3471)

**Comment by Justin-Arnold** [comment]
Thank you @AmmarCodes ! I went ahead and changed the image host and updated the link. Seems to be working now, but let me know if you have any other issues.

![CleanShot 2024-02-23 at 08 43 04@2x](https://github.com/Justin-Arnold/Journalyst/assets/87840654/7932ab2c-875e-4ad5-adf6-01a8eafc14d2)
