### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by oschrenk** [Justin-Arnold/Journalyst#2]
Was browsing through community plugins related to journaling and found yours. Installation fails via desktop UI.

New to Obsidian but maybe it has something to do with a missing 1.0.2 release in Github?

**Comment by Justin-Arnold** [comment]
You are absolutely right, It was missing a actual release for 1.0.2. I was able to reproduce it pretty easily and it is now fixed. Thank you, let me know if you have any other issues!
